version: "3.6"

services:
  gdoc-app-api:
    container_name: backend
    build: ./
    command: npm run startdev
    working_dir: /src/app/gdoc-api

    ports: 
      - "4000:4000"
    links:
      - mongoDb
      - redis
    volumes:
      - ./:/src/app/gdoc-api
      - /src/app/gdoc-api/node_modules/

  mongoDb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

